### ISSUE TITLE
How can we move from docker compose to kubernetes?

### ISSUE THREAD

**Issue by fadishaar84** [katanaml/katana-skipper#10]
Hello Andrej, 
I would like to ask about how to move from docker-compose to Kubernetes, do we have to use some tools like kompose or other tools, I appreciate if you could guide me a little bit about how to perform this conversion to run our services on Skipper not using docker compose but kubernetes. Thank you.

**Comment by abaranovskis-redsamurai** [comment]
Hi,

Kubernetes runs containers, docker-compose prepares images. Kubernetes runs containers from those images. You can build images with something else, if you don't prefer Docker. But this is not related to Kubernetes.

**Comment by fadishaar84** [comment]
Thanks for the answer.
