### ISSUE TITLE
Doc: How to add a new service with a new queue

### ISSUE THREAD

**Issue by ladrua** [katanaml/katana-skipper#12]
How do we add a new service with a new queue called `translator`?

1. I add a new router adding a new path for my new service defining a new prefix and tag named `translator`.
2. I create a new request model for my new service in models.py containing `task_type` and expect a type `translator` and a `payload`
3. I define a new service container with the correct variables and set my `SERVICE=translator` and `QUEUE_NAME=skipper_translator`

I am able to call the new endpoint and it returns:
```
task_id: "-", 
task_status: "Success", 
outcome: "<starlette.responses.JSONResponse object at 0x7ff2672dbed0>"
```

However the container is never triggered. 

What am I missing?

**Comment by abaranovskis-redsamurai** [comment]
Hey, you should check this tutorial video: https://www.youtube.com/watch?v=nXHDSehjxV0 I explain how to include new service. Let me know if it still doesnt work, I will debug it.

**Comment by ladrua** [comment]
Thank you for your reply, I have watched the video a few times and it explains well how to set up the service container, but now how to extend the api router and have the new endpoint associate to a new queue. I have it working when I reuse the `skipper_serving` queue.

**Comment by abaranovskis-redsamurai** [comment]
This is the flow to add new endpoint/service and router:

1. In workflow.json (workflow folder) add queue mapping. Use *_sync or *_async based on your service
2. In endpoint.py from api, add new router, same as other routers
3. Create new router in api/routers, same as boston or mobilenet

In this video, I talk more about routers: https://www.youtube.com/watch?v=SWedfF6ftpA
This one is about including a new service (JS): https://www.youtube.com/watch?v=d1HIOVuDMMc

**Comment by ladrua** [comment]
Seems like I was just missing the `workflow.json` setup. All working now. Thanks for your great work. I found it while trying to build the same thing :)
