### ISSUE TITLE
How to check if a service is running or not?

### ISSUE THREAD

**Issue by fadishaar84** [katanaml/katana-skipper#14]
I have a question regarding the availability of microservices created, how can we check if a service is running or not ?  So, for each service, we have an event receiver running using: python main.py, what if one service failed to run for some reason, how can we check by code if a certain service is running or not? In case the service is not running we need to show a message saying that this service is not running. Thank you.

**Comment by abaranovskis-redsamurai** [comment]
This is a good enhancement request. I will note it down to be implemented. Thanks.
