### ISSUE TITLE
How to propagate an error message from one service to another?

### ISSUE THREAD

**Issue by fadishaar84** [katanaml/katana-skipper#17]
Hi Andrej,
I have a question regarding the logger. Now if I have two services which are service1 and service2. From service1 I have produced an event to service2 which is responsible for storing a file. In case I have an exception happened on service2 I can only get this error message on service1 : 
{'error': 'Receiver exception', 'queue': 'storage', 'service_name': 'store_file', 'correlation_id': 'a14a53d7-4468-486d-a614-979bd6a3a5be'}.
How to get the actual error message that happened in service2 but from service1? I have tried to check the logger, but I can only get 'service logged' message when I tried to get the log using : http://127.0.0.1:5001/api/v1/skipper/logger/log_producer and http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver but I only got this response: 
{
  "status": "logged"
}

Where does this error logged? and if it is not logged how to log it and how to get it from other services? Thank you.

**Comment by abaranovskis-redsamurai** [comment]
Probably you can catch the exception and send logger event with relevant info. Not sure this is supported out of the box, but you can add this code.
