### ISSUE TITLE
Most stable version

### ISSUE THREAD

**Issue by INF800** [katanaml/katana-skipper#2]
Hi,

I want to build an [OCR project](https://github.com/gov-ai/ocr/issues/1) on top of your project. Can I know the commit ID of most stable version?

Thanks.

**Comment by abaranovskis-redsamurai** [comment]
Hey, thanks for your message, I'm happy to know you find it useful. Yes, you can build OCR app, you can add your own services by replacing current sample services under 'services' package. 

The current code is stable, I will create a release soon. You can use the current latest version.

We will be using this infra to build ML apps on top of it. I thought it is good to share the infra with the community :)

**Comment by abaranovskis-redsamurai** [comment]
> > Hey, thanks for your message, I'm happy to know you find it useful. Yes, you can build OCR app, you can add your own services by replacing current sample services under 'services' package.
> > The current code is stable, I will create a release soon. You can use the current latest version.
> > We will be using this infra to build ML apps on top of it. I thought it is good to share the infra with the community :)
> 
> It is really helpful indeed. I really love the way you have organised the docker containers

I created release tag, this way is simpler to find stable version: https://github.com/katanaml/katana-skipper/releases/tag/v1.0.0

**Comment by INF800** [comment]
> > > Hey, thanks for your message, I'm happy to know you find it useful. Yes, you can build OCR app, you can add your own services by replacing current sample services under 'services' package.
> > > The current code is stable, I will create a release soon. You can use the current latest version.
> > > We will be using this infra to build ML apps on top of it. I thought it is good to share the infra with the community :)
> > 
> > 
> > It is really helpful indeed. I really love the way you have organised the docker containers
> 
> I created release tag, this way is simpler to find stable version: https://github.com/katanaml/katana-skipper/releases/tag/v1.0.0

Awesome. I have started development here https://github.com/gov-ai/thinking
