### ISSUE TITLE
Docker-compose up not working

### ISSUE THREAD

**Issue by jamesee** [katanaml/katana-skipper#5]
Hi

Thank you for the wonderful katana-skipper.
I am trying to digest the library and execute the docker-compose.yml.
But it seems like it is not working.

Would appreciate it if you could take a look

**Comment by abaranovskis-redsamurai** [comment]
Hello,

Thanks for your question.

Are you following instructions from main README file? There is a command

```
docker-compose up --build -d
```

You should run this command from Skipper root folder. It works perfectly for me.

What errors you are getting? Maybe there are not enough resources set in your Docker setup?

**Comment by jamesee** [comment]
Hi Andrej

Thank you for your prompt reply.

If you could just execute the docker-compose command without the -d flag, you are likely to see the following logs which indicated errors and containers exited code 1.

=========================

Attaching to data-service, nginx_1, mobilenet-service, rabbitmq-service, serving-service, skipper-api, skipper-api-celery, skipper-logger, skipper-workflow, storage-service, training-service
rabbitmq-service    | touch: cannot touch '/etc/rabbitmq/rabbitmq.conf': Permission denied
rabbitmq-service    | 
rabbitmq-service    | WARNING: '/etc/rabbitmq/rabbitmq.conf' is not writable, but environment variables have been provided which request that we write to it
rabbitmq-service    |   We have copied it to '/tmp/rabbitmq.conf' so it can be amended to work around the problem, but it is recommended that the read-only source file should be modified and the environment variables removed instead.
rabbitmq-service    | 
skipper-workflow    | INFO:     Started server process [1]
skipper-workflow    | INFO:     Waiting for application startup.
skipper-workflow    | INFO:     Application startup complete.
skipper-workflow    | INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
skipper-logger      | INFO:     Started server process [1]
skipper-logger      | INFO:     Waiting for application startup.
skipper-logger      | INFO:     Application startup complete.
skipper-logger      | INFO:     Uvicorn running on http://0.0.0.0:5001 (Press CTRL+C to quit)
storage-service     | Traceback (most recent call last):
storage-service     |   File "storage_controller.py", line 20, in <module>
storage-service     |     main()
storage-service     |   File "storage_controller.py", line 16, in main
storage-service     |     'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))
storage-service     |   File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/exchange_receiver.py", line 15, in __init__
storage-service     |     credentials=credentials))
storage-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
storage-service     |     self._impl = self._create_connection(parameters, _impl_class)
storage-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
storage-service     |     raise self._reap_last_connection_workflow_error(error)
storage-service     | pika.exceptions.AMQPConnectionError
nginx_1             | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1             | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_1             | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_1             | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx_1             | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
nginx_1             | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_1             | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx_1             | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_1             | 2021/12/10 01:45:34 [notice] 1#1: using the "epoll" event method
nginx_1             | 2021/12/10 01:45:34 [notice] 1#1: nginx/1.21.4
nginx_1             | 2021/12/10 01:45:34 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
nginx_1             | 2021/12/10 01:45:34 [notice] 1#1: OS: Linux 5.10.76-linuxkit
nginx_1             | 2021/12/10 01:45:34 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx_1             | 2021/12/10 01:45:34 [notice] 1#1: start worker processes
nginx_1             | 2021/12/10 01:45:34 [notice] 1#1: start worker process 30
nginx_1             | 2021/12/10 01:45:34 [notice] 1#1: start worker process 31
nginx_1             | 2021/12/10 01:45:34 [notice] 1#1: start worker process 32
nginx_1             | 2021/12/10 01:45:34 [notice] 1#1: start worker process 33
storage-service exited with code 0
serving-service     | 2021-12-10 01:45:35.220627: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
serving-service     | 2021-12-10 01:45:35.224858: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
skipper-api         | INFO:     Started server process [1]
skipper-api         | INFO:     Waiting for application startup.
skipper-api         | INFO:     Application startup complete.
skipper-api         | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
storage-service     | Traceback (most recent call last):
storage-service     |   File "storage_controller.py", line 20, in <module>
storage-service     |     main()
storage-service     |   File "storage_controller.py", line 16, in main
storage-service     |     'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))
storage-service     |   File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/exchange_receiver.py", line 15, in __init__
storage-service     |     credentials=credentials))
storage-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
storage-service     |     self._impl = self._create_connection(parameters, _impl_class)
storage-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
storage-service     |     raise self._reap_last_connection_workflow_error(error)
storage-service     | pika.exceptions.AMQPConnectionError
training-service    | 2021-12-10 01:45:35.685240: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
training-service    | 2021-12-10 01:45:35.685300: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
storage-service exited with code 1
mobilenet-service   | 2021-12-10 01:45:35.935793: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
mobilenet-service   | To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
mobilenet-service   | /usr/src/mobilenetservice/node_modules/@katanaml/skipper-lib-js/skipper/events/event_receiver.js:16
mobilenet-service   |                 throw error0;
mobilenet-service   |                 ^
mobilenet-service   | 
mobilenet-service   | Error: connect ECONNREFUSED 172.22.0.4:5672
mobilenet-service   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
mobilenet-service   |   errno: -111,
mobilenet-service   |   code: 'ECONNREFUSED',
mobilenet-service   |   syscall: 'connect',
mobilenet-service   |   address: '172.22.0.4',
mobilenet-service   |   port: 5672
mobilenet-service   | }
data-service        | Traceback (most recent call last):
data-service        |   File "main.py", line 19, in <module>
data-service        |     main()
data-service        |   File "main.py", line 15, in main
data-service        |     'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))
data-service        |   File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/event_receiver.py", line 15, in __init__
data-service        |     credentials=credentials))
data-service        |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
data-service        |     self._impl = self._create_connection(parameters, _impl_class)
data-service        |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
data-service        |     raise self._reap_last_connection_workflow_error(error)
data-service        | pika.exceptions.AMQPConnectionError
mobilenet-service exited with code 1
skipper-api-celery  | /usr/local/lib/python3.7/site-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
skipper-api-celery  | absolutely not recommended!
skipper-api-celery  | 
skipper-api-celery  | Please specify a different user using the --uid option.
skipper-api-celery  | 
skipper-api-celery  | User information: uid=0 euid=0 gid=0 egid=0
skipper-api-celery  | 
skipper-api-celery  |   uid=uid, euid=euid, gid=gid, egid=egid,
skipper-api-celery  | [2021-12-10 01:45:36,822: ERROR/MainProcess] consumer: Cannot connect to amqp://skipper:**@rabbitmq:5672//: [Errno 111] Connection refused.
skipper-api-celery  | Trying again in 2.00 seconds... (1/100)
skipper-api-celery  | 
data-service exited with code 1
storage-service     | Traceback (most recent call last):
storage-service     |   File "storage_controller.py", line 20, in <module>
storage-service     |     main()
storage-service     |   File "storage_controller.py", line 16, in main
storage-service     |     'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))
storage-service     |   File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/exchange_receiver.py", line 15, in __init__
storage-service     |     credentials=credentials))
storage-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
storage-service     |     self._impl = self._create_connection(parameters, _impl_class)
storage-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
storage-service     |     raise self._reap_last_connection_workflow_error(error)
storage-service     | pika.exceptions.AMQPConnectionError
storage-service exited with code 1
skipper-api-celery  | [2021-12-10 01:45:38,835: ERROR/MainProcess] consumer: Cannot connect to amqp://skipper:**@rabbitmq:5672//: [Errno 111] Connection refused.
skipper-api-celery  | Trying again in 4.00 seconds... (2/100)
skipper-api-celery  | 
mobilenet-service   | 2021-12-10 01:45:38.974546: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
mobilenet-service   | To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
mobilenet-service   | /usr/src/mobilenetservice/node_modules/@katanaml/skipper-lib-js/skipper/events/event_receiver.js:16
mobilenet-service   |                 throw error0;
mobilenet-service   |                 ^
mobilenet-service   | 
mobilenet-service   | Error: connect ECONNREFUSED 172.22.0.4:5672
mobilenet-service   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
mobilenet-service   |   errno: -111,
mobilenet-service   |   code: 'ECONNREFUSED',
mobilenet-service   |   syscall: 'connect',
mobilenet-service   |   address: '172.22.0.4',
mobilenet-service   |   port: 5672
mobilenet-service   | }
storage-service     | Traceback (most recent call last):
storage-service     |   File "storage_controller.py", line 20, in <module>
storage-service     |     main()
storage-service     |   File "storage_controller.py", line 16, in main
storage-service     |     'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))
storage-service     |   File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/exchange_receiver.py", line 15, in __init__
storage-service     |     credentials=credentials))
storage-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
storage-service     |     self._impl = self._create_connection(parameters, _impl_class)
storage-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
storage-service     |     raise self._reap_last_connection_workflow_error(error)
storage-service     | pika.exceptions.AMQPConnectionError
mobilenet-service exited with code 1
storage-service exited with code 1
training-service    | Traceback (most recent call last):
training-service    |   File "main.py", line 19, in <module>
training-service    |     main()
training-service    |   File "main.py", line 15, in main
training-service    |     'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))
training-service    |   File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/event_receiver.py", line 15, in __init__
training-service    |     credentials=credentials))
training-service    |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
training-service    |     self._impl = self._create_connection(parameters, _impl_class)
training-service    |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
training-service    |     raise self._reap_last_connection_workflow_error(error)
training-service    | pika.exceptions.AMQPConnectionError
serving-service     | Traceback (most recent call last):
serving-service     |   File "main.py", line 19, in <module>
serving-service     |     main()
serving-service     |   File "main.py", line 15, in main
serving-service     |     'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))
serving-service     |   File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/event_receiver.py", line 15, in __init__
serving-service     |     credentials=credentials))
serving-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
serving-service     |     self._impl = self._create_connection(parameters, _impl_class)
serving-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
serving-service     |     raise self._reap_last_connection_workflow_error(error)
serving-service     | pika.exceptions.AMQPConnectionError
training-service exited with code 1
data-service        | Traceback (most recent call last):
data-service        |   File "main.py", line 19, in <module>
data-service        |     main()
data-service        |   File "main.py", line 15, in main
data-service        |     'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))
data-service        |   File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/event_receiver.py", line 15, in __init__
data-service        |     credentials=credentials))
data-service        |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
data-service        |     self._impl = self._create_connection(parameters, _impl_class)
data-service        |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
data-service        |     raise self._reap_last_connection_workflow_error(error)
data-service        | pika.exceptions.AMQPConnectionError
storage-service     | Traceback (most recent call last):
storage-service     |   File "storage_controller.py", line 20, in <module>
storage-service     |     main()
storage-service     |   File "storage_controller.py", line 16, in main
storage-service     |     'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))
storage-service     |   File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/exchange_receiver.py", line 15, in __init__
storage-service     |     credentials=credentials))
storage-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
storage-service     |     self._impl = self._create_connection(parameters, _impl_class)
storage-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
storage-service     |     raise self._reap_last_connection_workflow_error(error)
storage-service     | pika.exceptions.AMQPConnectionError
serving-service exited with code 0
mobilenet-service   | 2021-12-10 01:45:42.328536: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
mobilenet-service   | To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
mobilenet-service   | /usr/src/mobilenetservice/node_modules/@katanaml/skipper-lib-js/skipper/events/event_receiver.js:16
mobilenet-service   |                 throw error0;
mobilenet-service   |                 ^
mobilenet-service   | 
mobilenet-service   | Error: connect ECONNREFUSED 172.22.0.4:5672
mobilenet-service   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
mobilenet-service   |   errno: -111,
mobilenet-service   |   code: 'ECONNREFUSED',
mobilenet-service   |   syscall: 'connect',
mobilenet-service   |   address: '172.22.0.4',
mobilenet-service   |   port: 5672
mobilenet-service   | }
skipper-api-celery  | [2021-12-10 01:45:42,880: ERROR/MainProcess] consumer: Cannot connect to amqp://skipper:**@rabbitmq:5672//: [Errno 111] Connection refused.
skipper-api-celery  | Trying again in 6.00 seconds... (3/100)
skipper-api-celery  | 
training-service    | 2021-12-10 01:45:43.014523: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
training-service    | 2021-12-10 01:45:43.016595: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
data-service exited with code 0
storage-service exited with code 1
serving-service     | 2021-12-10 01:45:44.992438: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
serving-service     | 2021-12-10 01:45:44.992629: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
mobilenet-service exited with code 0
storage-service     | Traceback (most recent call last):
storage-service     |   File "storage_controller.py", line 20, in <module>
storage-service     |     main()
storage-service     |   File "storage_controller.py", line 16, in main
storage-service     |     'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))
storage-service     |   File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/exchange_receiver.py", line 15, in __init__
storage-service     |     credentials=credentials))
storage-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
storage-service     |     self._impl = self._create_connection(parameters, _impl_class)
storage-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
storage-service     |     raise self._reap_last_connection_workflow_error(error)
storage-service     | pika.exceptions.AMQPConnectionError
storage-service exited with code 1
mobilenet-service   | 2021-12-10 01:45:47.987048: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
mobilenet-service   | To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
data-service        | Traceback (most recent call last):
data-service        |   File "main.py", line 19, in <module>
data-service        |     main()
data-service        |   File "main.py", line 15, in main
data-service        |     'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))
data-service        |   File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/event_receiver.py", line 15, in __init__
data-service        |     credentials=credentials))
data-service        |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
data-service        |     self._impl = self._create_connection(parameters, _impl_class)
data-service        |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
data-service        |     raise self._reap_last_connection_workflow_error(error)
data-service        | pika.exceptions.AMQPConnectionError
mobilenet-service   | /usr/src/mobilenetservice/node_modules/@katanaml/skipper-lib-js/skipper/events/event_receiver.js:16
mobilenet-service   |                 throw error0;
mobilenet-service   |                 ^
mobilenet-service   | 
mobilenet-service   | Error: connect ECONNREFUSED 172.22.0.4:5672
mobilenet-service   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
mobilenet-service   |   errno: -111,
mobilenet-service   |   code: 'ECONNREFUSED',
mobilenet-service   |   syscall: 'connect',
mobilenet-service   |   address: '172.22.0.4',
mobilenet-service   |   port: 5672
mobilenet-service   | }
mobilenet-service exited with code 1
data-service exited with code 1
skipper-api-celery  | [2021-12-10 01:45:48,899: ERROR/MainProcess] consumer: Cannot connect to amqp://skipper:**@rabbitmq:5672//: [Errno 111] Connection refused.
skipper-api-celery  | Trying again in 8.00 seconds... (4/100)
skipper-api-celery  | 
training-service    | Traceback (most recent call last):
training-service    |   File "main.py", line 19, in <module>
training-service    |     main()
training-service    |   File "main.py", line 15, in main
training-service    |     'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))
training-service    |   File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/event_receiver.py", line 15, in __init__
training-service    |     credentials=credentials))
training-service    |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
training-service    |     self._impl = self._create_connection(parameters, _impl_class)
training-service    |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
training-service    |     raise self._reap_last_connection_workflow_error(error)
training-service    | pika.exceptions.AMQPConnectionError
training-service exited with code 1
serving-service     | Traceback (most recent call last):
serving-service     |   File "main.py", line 19, in <module>
serving-service     |     main()
serving-service     |   File "main.py", line 15, in main
serving-service     |     'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))
serving-service     |   File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/event_receiver.py", line 15, in __init__
serving-service     |     credentials=credentials))
serving-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
serving-service     |     self._impl = self._create_connection(parameters, _impl_class)
serving-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
serving-service     |     raise self._reap_last_connection_workflow_error(error)
serving-service     | pika.exceptions.AMQPConnectionError
storage-service     | Traceback (most recent call last):
storage-service     |   File "storage_controller.py", line 20, in <module>
storage-service     |     main()
storage-service     |   File "storage_controller.py", line 16, in main
storage-service     |     'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))
storage-service     |   File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/exchange_receiver.py", line 15, in __init__
storage-service     |     credentials=credentials))
storage-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
storage-service     |     self._impl = self._create_connection(parameters, _impl_class)
storage-service     |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
storage-service     |     raise self._reap_last_connection_workflow_error(error)
storage-service     | pika.exceptions.AMQPConnectionError
serving-service exited with code 1
storage-service exited with code 1
mobilenet-service   | 2021-12-10 01:45:51.791578: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
mobilenet-service   | To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
mobilenet-service   | /usr/src/mobilenetservice/node_modules/@katanaml/skipper-lib-js/skipper/events/event_receiver.js:16
mobilenet-service   |                 throw error0;
mobilenet-service   |                 ^
mobilenet-service   | 
mobilenet-service   | Error: connect ECONNREFUSED 172.22.0.4:5672
mobilenet-service   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
mobilenet-service   |   errno: -111,
mobilenet-service   |   code: 'ECONNREFUSED',
mobilenet-service   |   syscall: 'connect',
mobilenet-service   |   address: '172.22.0.4',
mobilenet-service   |   port: 5672
mobilenet-service   | }
training-service    | 2021-12-10 01:45:52.077951: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
training-service    | 2021-12-10 01:45:52.078019: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
mobilenet-service exited with code 1
data-service        | Traceback (most recent call last):
data-service        |   File "main.py", line 19, in <module>
data-service        |     main()
data-service        |   File "main.py", line 15, in main
data-service        |     'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))
data-service        |   File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/event_receiver.py", line 15, in __init__
data-service        |     credentials=credentials))
data-service        |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
data-service        |     self._impl = self._create_connection(parameters, _impl_class)
data-service        |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
data-service        |     raise self._reap_last_connection_workflow_error(error)
data-service        | pika.exceptions.AMQPConnectionError
data-service exited with code 1
serving-service     | 2021-12-10 01:45:52.867265: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
serving-service     | 2021-12-10 01:45:52.867354: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
training-service    | Traceback (most recent call last):
training-service    |   File "main.py", line 19, in <module>
training-service    |     main()
training-service    |   File "main.py", line 15, in main
training-service    |     'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))
training-service    |   File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/event_receiver.py", line 15, in __init__
training-service    |     credentials=credentials))
training-service    |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
training-service    |     self._impl = self._create_connection(parameters, _impl_class)
training-service    |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
training-service    |     raise self._reap_last_connection_workflow_error(error)
training-service    | pika.exceptions.AMQPConnectionError
training-service exited with code 1

**Comment by abaranovskis-redsamurai** [comment]
Hello,

You can ignore these errors. Services are trying to connect to RabbitMQ while starting, but RabbitMQ is not ready yet. Services are restarting automatically, based on the policy provided in Docker script, as soon as RabbitMQ is up, these services will be up and running too.

Give it a minute, after Docker script completes, then check with:

```
docker ps -a
```

API should be accessible by this URL: http://127.0.0.1:8080/api/v1/skipper/tasks/docs

**Comment by jamesee** [comment]
May I know what should be the payload ?

<img width="652" alt="Screenshot 2021-12-11 at 00 56 29" src="https://user-images.githubusercontent.com/37786118/145612377-7161f8a0-0ebb-433e-be10-68f4b1cbcc9c.png">

**Comment by abaranovskis-redsamurai** [comment]
You can use 0.2, this means 20% of data in sample training service will be used for test dataset.

**Comment by jamesee** [comment]
thanks Andrej.
