### ISSUE TITLE
The difference between event_producer and exchange_producer

### ISSUE THREAD

**Issue by fadishaar84** [katanaml/katana-skipper#6]
Hello, 
Thanks for sharing your ML workflow. I appreciate if you could explain the difference between event_producer and exchange_producer. event_producer is used to produce an event to rabbitmq, but exchange_producer is not clear to me. Can't we use event_producer in place of exchange_producer?

**Comment by abaranovskis-redsamurai** [comment]
Hello,

Good question, let me explain.

exchange_producer is also producing an event for RabbitMQ. But this is a different type of event. event_producer implements RPC (remote procedure call) pattern, it sends event and waits for a response. If there are multiple subscribers, events will be distributed in a round-robin fashion, one by one. Contrary to Exchange, the event will be sent in fanout mode, to all subscribers at once and there will be no response expected. These two are different ways to send events through RabbitMQ.

I'm using exchange_producer to send notification events to a serving container when a new model is trained. If there are multiple instances of serving containers in Kubernetes, all of them will get that notification.

RPC: https://www.rabbitmq.com/tutorials/tutorial-six-python.html
Exchange: https://www.rabbitmq.com/tutorials/tutorial-four-python.html

Hope this explains it.

**Comment by fadishaar84** [comment]
Thanks for your answer, it is clear now. exchange_producer is working to broadcast messages to all subscribers without waiting for a response. But regarding serving service, I have not seen exchange_producer is used but I have seen you use it at the end of training service to notify the storage service for saving the trained model.

**Comment by fadishaar84** [comment]
Thanks a lot for your quick response.
