### ISSUE TITLE
Cache EventProducer

### ISSUE THREAD

**Issue by manhtd98** [katanaml/katana-skipper#8]
I found that cache the EventProducer can improve performace 40%. I tried but it block may request when increase the speed test. Do you have suggest to fix that

**Comment by abaranovskis-redsamurai** [comment]
Hello.

Interesting. What do you mean by cache the EventProducer? Could you explain, please?

Thanks,
Andrej

**Comment by manhtd98** [comment]
```
from fastapi.responses import JSONResponse
import json
from skipper_lib.events.event_producer import EventProducer
import skipper_lib.workflow.workflow_helper as workflow_helper
import os

event_producer = EventProducer(username=os.getenv('RABBITMQ_USER', 'skipper'),
                                   password=os.getenv('RABBITMQ_PASSWORD', 'welcome1'),
                                   host=os.getenv('RABBITMQ_HOST', '127.0.0.1'),
                                   port=os.getenv('RABBITMQ_PORT', 5672),
                                   service_name='api_sync',
                                   logger=os.getenv('LOGGER_PRODUCER_URL',
                                                    'http://127.0.0.1:5001/api/v1/skipper/logger/log_producer'))
def sync_request_helper(workflow_task_data):
    payload = workflow_task_data.json()

    queue_name = workflow_helper.call(workflow_task_data.task_type,
                                      os.getenv('WORKFLOW_URL',
                                                'http://127.0.0.1:5000/api/v1/skipper/workflow/'),
                                      '_sync')

    if queue_name is '-':
        return JSONResponse(status_code=202,
                            content={'task_id': '-',
                                     'task_status': 'Wrong task type'})

    
    response = json.loads(event_producer.call(queue_name, payload))

    return response
```
Just change to that and the event_producer not call anytime system call new request. it make 1 request from 30milisecond to 20milisecond

**Comment by abaranovskis-redsamurai** [comment]
Ok, that makes sense, very good suggestion, thanks. But you should test if there are no issues when there are multiple requests running in parallel, because the same instance of EventProducer will be shared.

I don't have the answer to your question about request blocking. I haven't seen this in my environment.

**Comment by manhtd98** [comment]
@abaranovskis-redsamurai  it block when i share the same EventProducer.

**Comment by manhtd98** [comment]
can you explain about celery. i saw that data direct send to RabbitMQ. Celery is likely do nothing

**Comment by abaranovskis-redsamurai** [comment]
That's why is implemented without sharing :)

Celery handles in Skipper, async requests, and task queue is managed through Celery.

**Comment by manhtd98** [comment]
@abaranovskis-redsamurai  thank you for clearly explain
